server:
  port: 8401
spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: http://82.157.65.202:8848/
        namespace: a6fcef0a-9dd2-4f9a-a109-f63a8ec54e80
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
      eager: true

management:
  endpoints:
    web:
      exposure:
        include: "*"