server:
  port: 3344

spring:
  application:
    name: majortom-cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MajorHorse/majortom-cloud-config.git
          search-paths:
            - majortom-cloud-config
          username: mylove103@foxmail.com
          password: maguo103
      label: main
  #rabbitmq 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka