server:
  port: 2003

spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://82.157.65.202:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: http://82.157.65.202:8848/
        namespace: a6fcef0a-9dd2-4f9a-a109-f63a8ec54e80
        group: SEATA_GROUP
    alibaba:
      seata:
        tx-service-group: myGroup
#seata:
#  registry:
#    type: nacos
#    preferred-networks: 30.240.*
#    nacos:
#      application: seata-server
#      server-addr: 82.157.65.202:8848
#      namespace: a6fcef0a-9dd2-4f9a-a109-f63a8ec54e80
#      group: SEATA_GROUP
#      username: nacos
#      password: maguo103
#      data-id: seata-server.properties
#  config:
#    type: nacos
#    nacos:
#      server-addr: 82.157.65.202:8848
#      namespace: a6fcef0a-9dd2-4f9a-a109-f63a8ec54e80
#      group: SEATA_GROUP
#      username: nacos
#      password: maguo103
#      data-id: seata-server.properties
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.majortom.cloud.domain
logging:
  level:
    io:
      seata: info
