server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  cloud:
    nacos:
      discovery:
        server-addr: 82.157.65.202:8848
  config:
    import:
      - optional:nacos:seata-client-demo.yml
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.majortom.cloud.domain
seata:
  service:
    vgroup-mapping:
      default_tx_group: default
      grouplist:
        default: 82.157.65.202:8091
logging:
  level:
    io:
      seata: info
