server:
  port: 8006

spring:
  application:
    name: majortom-provider-consul-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majortom_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}