server:
  port: 9527

spring:
  application:
    name: majortom-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh
          uri: lb://majortom-payment-service
          predicates:
            - Path=/payment/get/**
        - id: payment_routh2
          uri: lb://majortom-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka

