server:
  port: 7001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/majortom_cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1234
eureka:
  instance:
    hostname: eureka7001
  client:
    #false 表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己端就是注册中心
    fetch-registry: false
    service-url:
#      defaultZone: http://localhost:7002/eureka/
      defaultZone: http://localhost:7001/eureka/